// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver'
import assert from 'assert'

describe('tarasowski', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Click on leave your feedback', async function() {
    await driver.get("https://www.tarasowski.de/")
    await driver.manage().window().setRect({ width: 1512, height: 944 })
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.linkText("Leave your feedback")).click()
    vars["win3227"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win3227"])
    await driver.close()
    await driver.switchTo().window(vars["root"])
  })
})
